name: models
description: Dart package which manages the domain models.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.5.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.2
  very_good_analysis: ^3.0.2
