name: mikhuy
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <=3.0.0"
  flutter: 3.10.0
dependencies:
  authentication:
      path: packages/authentication
  bloc: ^8.1.0
  cloud_firestore: ^4.8.4
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.7
  formz: ^0.4.1
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.2.1
  intl: ^0.18.1
  label_marker: ^1.0.1
  location: ^5.0.3
  material_design_icons_flutter: ^7.0.7296
  models:
    path: packages/models
  permission_handler: ^10.2.0
  qr_flutter: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.6
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_icons:
  android: true
  image_path: "assets/logo-mikhuy.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo-mikhuy-foreground.png"
