name: Pre-release deployment for android

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get
        name: Downloading packages
      
      - run: flutter build apk --split-per-abi
        name: Building apk

      - name: Uploading apk to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifact: "build/app/outputs/flutter-apk/*.apk"
          prerelease: true